---

- hosts: localhost
  vars: 
    somelist: 
  tasks:
    - name: Update Ansible Tower inventory
      uri:
        url: https://closvl2120.cloud.volvocars.net/api/v2/inventories/
        user: admin
        password: "{{ ansibleadminpassword }}"
        method: POST
        body_format: json
        force_basic_auth: yes
 #body: "{ "name": "{{ Changenumber }}" , "description": "{{ Changenumber }}" , "organisation": 1}"
 body:
        name: "{{ Changenumber }}"
        description: "{{ Changenumber }}"
        organization: 1
        validate_certs: no
        return_content: yes
        status_code: 201
      register: output123 

    - name: "Debug"
      debug:
        msg: "{{ output123 }}"

    - name: "Create the host "
      uri:
        url: https://closvl2120.cloud.volvocars.net/api/v2/inventories/"{{ output123.content_id }}"/hosts/
        user: admin
        password: "{{ ansibleadminpassword }}"
        method: POST
        body_format: json 
        force_basic_auth: yes
        status_code: 201
        return_content: yes
        validate_certs: no
        body:
          name: "{{ somelist }}"



