---

- hosts: localhost
  vars: 
    somelist: 
  tasks:
    - name: Update Ansible Tower inventory
      uri:
        url: https://13.235.245.87/api/v2/inventories/
        user: admin
        password: redhat
        method: POST
        body_format: json
        force_basic_auth: yes
 #body: "{ "name": "{{ Changenumber }}" , "description": "{{ Changenumber }}" , "organisation": 1}"
        body:
          name: inv
          organization: 1
        validate_certs: no
        return_content: yes
        status_code: 201
      register: output123 

    - name: "Debug"
      debug:
        msg: "{{ output123 }}"

   



