---

- hosts: localhost
  vars: 
    somelist: 
  tasks:
    - name: "Create the host "
      uri:
        url: https://13.235.245.87/api/v2/inventories/4/hosts/
        user: admin
        password: redhat
        method: POST
        body_format: json
        force_basic_auth: yes
        status_code: 201
        return_content: yes
        validate_certs: no
        body:
          name: "{{ somelist }}"
   



